### ISSUE TITLE
Add theme to Linear site

### ISSUE THREAD

**Issue by zenorocha** [jamieshiers/Dracula-for-Linear#1]
Hey @jamieshiers, can you add the theme to https://linear.style?

Instructions: https://github.com/alii/linear-style/blob/main/README.md

**Comment by jamieshiers** [comment]
Done! Just waiting for it to be merged.

[https://github.com/alii/linear-style/pull/39](https://github.com/alii/linear-style/pull/39)

**Comment by zenorocha** [comment]
👍
